# -*- coding: utf-8 -*-
"""Practical_Test1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18aBJZ_3WcnqhsI4wlJWk2xPUXTtfp2De
"""

#1. Given a number count the total number of digits in a number
#For example: The number is 75869, so the output should be 5

num=int(input("Enter Number: "))
counter=0
temp=num
while num!=0:
  num=num//10
  counter+=1
print("The total number of digits in",temp,' is ',counter)

#1Reverse the following list using for loop
#list1 = [10, 20, 30, 40, 50]

l=[]
while True:
  data=input("Enter Values: ")
  if data=='':
    break
  l.append(data)  
print("Original list")
print(l)
rw=l[::-1]
print("Reversed list")
print(rw)

#2. Given 2 strings, s1 and s2, create a new string by appending s2 in the middle of s1
#Expected Outcome:
#appendMiddle("Chrisdem", IamNewString) → "ChrIamNewStringisdem"

def appendMiddle(str1,str2):
    
    mid_str = (len(str1)//2)
    return str1[:mid_str] + str2 + str1[mid_str:]

appendMiddle("Chrisdem", "IamNewString")

'''3. Arrange String characters such that lowercase letters should come first
Given input String of combination of the lower and upper case arrange characters in such a way that all
lowercase letters should come first.
Expected Output:
input_String = PyNaTive
arranging characters giving precedence to lowercase letters
aeiNPTvy
arranging characters giving precedence to lowercase letters:
yaivePNT'''

ip_str = input("Enter your input :- ")

low_char = ""
upp_char = ""

for i in ip_str:

  if i.islower():
    low_char += i
  else:
    upp_char += i

result = low_char+upp_char
print(result)

'''4. Given a string, return the sum and average of the digits that appear in the string, ignoring all other
characters
For Example: –
sumAndAverage("English = 78 Science = 83 Math = 68 History = 65") = sum 294 Percentage is 73.5'''

def sumAndAverage(ip_str):
  l= ip_str.split()
  num_list = []
  
  for i in l:
    if i.isnumeric():
      num_list.append(int(i))

  digit_sum = sum(num_list)
  digit_avg = digit_sum/len(num_list)

  return "Sum :- " + str(digit_sum) + " Avg :-" + str(digit_avg)

sumAndAverage('English = 78 Science = 83 Math = 68 History = 65") = sum 294 Percentage is 73.5')

'''5. Given a two list. Create a third list by picking an odd-index element from the first list and even index
elements from second.
For Example:
listOne = [3, 6, 9, 12, 15, 18, 21]
listTwo = [4, 8, 12, 16, 20, 24, 28]
Expected Output:
Element at odd-index positions from list one
[6, 12, 18]
Element at even-index positions from list two
[4, 12, 20, 28]
Printing Final third list
[6, 12, 18, 4, 12, 20, 28]'''

list1=[]
while True:
  data=input("Enter Values: ")
  if data=='':
    break
  list1.append(data)

list2=[]
while True:
  data=input("Enter Values: ")
  if data=='':
    break
  list2.append(data)
odd_list = [list1[i] for i in range(len(list1)) if int(i)%2!=0]
even_list = [list2[i] for i in range(len(list2)) if int(i)%2==0]

final_list = odd_list + even_list

print("Element at odd-index positions from list one",
      odd_list,
      "Element at even-index positions from list two",
      even_list,
      "Printing Final third list",
      final_list,sep = "\n")