# -*- coding: utf-8 -*-
"""Assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19SH73erskH6AVYgSm2-imlHASnNG9qKH
"""

#1.	Write apythonprogram to solve the quadratic equation, ax2 + bx + python – 0. Consider all possibilities of input data.

#2.	Suppose rs.5,000/- is deposited each year in an account which yields 10% interest compounded annually. Write a program which prints the amount in the account at the 
#End of each year for 10 years.

p = float(input("Enter the principle amount : "))
r = float(input("Enter the rate of interest : "))
t = float(input("Enter the time in the years: "))

ci =  p * (pow((1 + r / 100), t)) 

print("compound Interest : ", ci)

#3.	Write a python program to display (even) or [odd] words for the input of integer number using python library functions. Draw the flowchart also.

num=int(input("Enter number:"))
if (num%2==0):
  print(num,"is Even")
else:
  print(num,"is odd")

#4.	Write a python program, which will read two unequal integer numbers and shall print out both the numbers at the output in descending order.
n1,n2=int(input("Enter num1:")),int(input("Enter num2:"))
if n1<n2:
  print(n2,n1)
else:
  print(n1,n2)

#5.	Write a python program, which will read three unequal numbers and shall output the largest of the three.

no1,no2,no3=int(input("Enter num1:")),int(input("Enter num2:")),int(input("Enter num3:"))
if(no1>no2 and no1>no3):
  print("Max is:",no1)
elif no2>no3:
  print("Max is:",no2)
else:
  print("Max is:",no3)

#6.	Write a python program, which will read three unequal integers and shall output all the three integers in decreasing order.
num1,num2,num3=int(input("Enter num1:")),int(input("Enter num2:")),int(input("Enter num3:"))

if num1>num2 and num1>num3:
  if num2>num3:
    print(num1,num2,num3)
  else:
    print(num1,num3,num2)

elif num2>num3:
  if num3>num1:
    print(num2,num3,num1)
  else:
    print(num2,num1,num3)

else:
  if num2>num1:
    print(num3,num2,num1)
  else:
    print(num3,num1,num2)

#7.	Develop a program to accept a year as input and printout if it is a leap year or not. A year is a leap year if it is divisible by 4 and 
#centennial years (years divisible by 100 are leap years only when they are also divisible by 400.)

year=int(input("Enter Year:"))

if (year%4==0 and year%100!=0) or (year%400==0):
  print(year,"is a leap year")
else:
  print(year,"is not a leap year")

#8.	Write a program in python to display month in words (month number is input).
mon=int(input("Enter month:"))

if mon==1:
  print("January")
elif mon==2:
  print("Feburary")
elif mon==3:
  print("March")
elif mon==4:
  print("April")
elif mon==5:
  print("May")
elif mon==6:
  print("June")
elif mon==7:
  print("July")
elif mon==8:
  print("August")
elif mon==9:
  print("September")
elif mon==10:
  print("October")
elif mon==11:
  print("November")
elif mon==12:
  print("December")
else:
  print("Enter valid month number")

#9.	Write the menu driven program in ‘c’ language to perform the trignometric functional calculator for the following functions. 
#S – sin (x)			c – cos (x)
#T – tan (x)			x – quit

#11.	Write a python program, which will print will first 100 natural numbers.
for i in range(1,101):
    print(i,end=" ")

#12.	Write a program for summation of all the natural numbers up to and including the given integer.

num=int(input("Enter Number"))
if num < 0:
   print("Enter a positive number")
else:
   sum = 0
   while(num > 0):
       sum += num
       num -= 1
   print("The sum is", sum)

#13.	Write a program which reads and multiplies together 20 real numbers.
# (floating point numbers).

#14.	Write a python program, which will print in a tabular from all the alphabets, capital as well as lower case letters with their ascii values.

for c in range(97, 123):
  print(chr(c), end = " ")
  print("")

for c in range(65, 91):
  print(chr(c), end = " ")
  print("");

#15.	Write a program to read marks of 100 students and find all print the number of students passed in first class. The marks are out of 100 and to get first class one 
#has to obtain minimum 60 marks. Write a program, which will find and print sum of first 100 odd numbers.

#16.	Given a number, write a python program using while lop to reverse the digits of the number.	     
#E.g. If number is 31241 then output will be 14213.

num=int(input("Enter Number: "))  
temp=num  
rev=0    
while(num > 0):    
    rem=num %10    
    rev=(rev *10) + rem    
    num=num //10    
     
print("\n Reverse of entered number",temp," is:",rev)

#17.	Write the python program to reverse the input four-digit number. 
num=int(input("Enter Number: "))  
temp=num  
rev=0    
while(num > 0):    
    rem=num %10    
    rev=(rev *10) + rem    
    num=num //10    
     
print("\n Reverse of entered number",temp," is:",rev)

#18.	Modify the above python program to separate the individual digits of the four-digit number and display. Also get the sum of the separated digits of same four-digit number.
#Input no.	1234				output 	4321
#Separated digits 1, 2, 3, 4,		sum = 1+2+3+4 = 10
num=int(input("Enter Number: "))  
temp=num  
rev=0    
sum=0
while(num > 0):    
    rem=num %10    
    rev=(rev *10) + rem  
    sum+=rem  
    num=num //10    
     
print("\n Reverse of entered number",temp," is:",rev)
print("Sum of digits is:",sum)

#19.	Write a python program, which will read a positive integer number and shall print out whether it’s an armstrong number.
#An armstrong number is one the sum of cubes of whose digits equal the number itself (e.g. 13+53+33=153).

num=int(input("Enter Number:"))
temp=num
sum=0

while num!=0:
  rem=num%10
  sum=sum+(rem**3)
  num=num//10

if sum==temp:
  print(temp,"is a Armstrong number")
else:
  print(temp,"is not a Armstrong number")

#20.	Write a program which finds four digit perfect squares, where the number represented by 		e.g. 1681 = 412	16=42		81=912

#21.	Write a python program to calculate y where y=x^n where y, x are real and n is natural no.
x=float(input("Enter number:"))
n=int(input("Enter number:"))

y=x**n
print(y)

#22.	Write a program to print a “4 times table” in the following form:				 
#i.	1 * 4 = 4
#ii.	2 * 4 = 8
#iii.	3 * 4 = 12
#iv.	4 * 4 = 16	……… etc.

i=1
while i<=10:
  print(i,"*",4,"=",i*4)
  i+=1

#23.	Write a python program, which will read an integer and shall print out multiplication table of that integer.

num=int(input("Enter Number:"))

i=1
while i<=10:
  print(num,"*",i,"=",i*num)
  i+=1

#24.	Write a program in python to calculate factorial of given number.	
num=int(input("Enter number:"))
fact=1
if num==1:
  print("The factorial of",num,"is",fact)
else:
  for i in range(2,num + 1):
       fact = fact*i
  print("The factorial of",num,"is",fact)

#25.	Write a menu driven program to perform arithmetic functions. 1 for addition, 2 for subtraction, 3 for multiplication, 4 to exit, 
#program will quit only if the option is 4 else it reads option and calls respective function.

print("Enter 1 for addition")
print("Enter 2 for subtraction")
print("Enter 3 for multiplication")
print("Enter 4 for exit")

choice=int(input("Enter choice:"))

while True:
  if choice==1:
    num1=int(input("Enter Num1:"))
    num2=int(input("Enter Num2:"))
    print(num1,"+",num2,"=",num1+num2)
    break
  if choice==2:
    num1=int(input("Enter Num1:"))
    num2=int(input("Enter Num2:"))
    print(num1,"-",num2,"=",num1-num2)
    break
  if choice==3:
    num1=int(input("Enter Num1:"))
    num2=int(input("Enter Num2:"))
    print(num1,"*",num2,"=",num1*num2)
    break
  if choice==4:
    break

#26.	Write a program that reads numbers until a negative number is read, and prints
#i)	Number of values read,
#ii)	The largest value and
#iii)	The smallest value

#27.	Write a python program to display months in words where month in number is input.
mon=int(input("Enter month:"))

if mon==1:
  print("January")
elif mon==2:
  print("Feburary")
elif mon==3:
  print("March")
elif mon==4:
  print("April")
elif mon==5:
  print("May")
elif mon==6:
  print("June")
elif mon==7:
  print("July")
elif mon==8:
  print("August")
elif mon==9:
  print("September")
elif mon==10:
  print("October")
elif mon==11:
  print("November")
elif mon==12:
  print("December")
else:
  print("Enter valid month number")

#28.	Write a python program to generate the first n prime numbers

numr=int(input("Enter range:"))
print("Prime numbers:",end=' ')

for n in range(1,numr):
    for i in range(2,n):
        if(n%i==0):
            break
    else:
        print(n,end=' ')

#29.	Write a python program to read two natural numbers r1 and r2, where r2 is greater than r1 and to generate all the prime numbers between r1 and r2 both inclusive.

#30.	Write a python program to find factorial of given number.
#Menu driven program to 1.add 2.sud 3.mul 4.exit
#Program will quit when 4 is input else cal respective function to perform given operation.

num=int(input("Enter number:"))
fact=1
if num==1:
  print("The factorial of",num,"is",fact)
else:
  for i in range(2,num + 1):
       fact = fact*i
  print("The factorial of",num,"is",fact)

print("Enter 1 for addition")
print("Enter 2 for subtraction")
print("Enter 3 for multiplication")
print("Enter 4 for exit")

choice=int(input("Enter choice:"))

while True:
  if choice==1:
    num1=int(input("Enter Num1:"))
    num2=int(input("Enter Num2:"))
    print(num1,"+",num2,"+",num1+num2)
    break
  if choice==2:
    num1=int(input("Enter Num1:"))
    num2=int(input("Enter Num2:"))
    print(num1,"-",num2,"=",num1-num2)
    break
  if choice==3:
    num1=int(input("Enter Num1:"))
    num2=int(input("Enter Num2:"))
    print(num1,"*",num2,"=",num1*num2)
    break
  if choice==4:
    break

#31.	Suppose you place a given sum of money, a, into a savings account at the beginning of each year for n years. 
#If the account earns interest at the rate or i percent annually, then the amount of money that have accumulated after n years, f is given by 
#F = a[(1+i\100)+(1+1/100)2+1(1+1/100)3+………….+(1+1/100)n]
#Write an interactive python program to determine money gets accumulated at the end of n years.

#32.	Conjecture holds that all positive integers converges to 1 (one) when treated in the following fashion.										
#•	If the number is odd, it is multiplied by three and one is added.
#•	If the number is even, it is divided by two.
#continuously apply above operations to the intermediate results until the number converges to one. 
#Write a program to read an integer number form keyboard and implement the above mentioned algorithm and display all the intermediate values.