# -*- coding: utf-8 -*-
"""Dictionary_DS_Programs.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14E1yp87KEta2MSYC78x2llh9YI4AvxhE
"""

#Python provides the built-in function dict() method which is also used to create dictionary. The empty curly braces {} is used to create empty dictionary.

# Creating an empty Dictionary   
Dict = {}   
print("Empty Dictionary: ")   
print(Dict)   
  
# Creating a Dictionary   
# with dict() method   
Dict = dict({1: 'Java', 2: 'T', 3:'Point'})   
print("\nCreate Dictionary by using  dict(): ")   
print(Dict)   
  
# Creating a Dictionary   
# with each item as a Pair   
Dict = dict([(1, 'Devansh'), (2, 'Sharma')])   
print("\nDictionary with each item as a pair: ")   
print(Dict)

# for loop to print all the keys of a dictionary

Employee = {"Name": "John", "Age": 29, "salary":25000,"Company":"GOOGLE"}    
for x in Employee:    
    print(x)

#for loop to print all the values of the dictionary

Employee = {"Name": "John", "Age": 29, "salary":25000,"Company":"GOOGLE"}    
for x in Employee:    
    print(Employee[x])

#for loop to print the values of the dictionary by using values() method.

Employee = {"Name": "John", "Age": 29, "salary":25000,"Company":"GOOGLE"}    
for x in Employee.values():    
    print(x)

#for loop to print the items of the dictionary by using items() method.

Employee = {"Name": "John", "Age": 29, "salary":25000,"Company":"GOOGLE"}    
for x in Employee.items():    
    print(x)

#2. In python, the key cannot be any mutable object. We can use numbers, strings, or tuples as the key, 
#but we cannot use any mutable object like the list as the key in the dictionary.



Employee = {"Name": "John", "Age": 29, "salary":25000,"Company":"GOOGLE",[100,201,301]:"Department ID"}    
for x,y in Employee.items():    
    print(x,y)

#Write a Python program to sort (ascending and descending) a dictionary by value.

import operator
d = {1: 2, 3: 4, 4: 3, 2: 1, 0: 0}
print('Original dictionary : ',d)

sorted_d = sorted(d.items(), key=operator.itemgetter(1))
#sorted() gives output in the form of list

print('Dictionary in ascending order by value : ',sorted_d)
#here we can see that as the sorted output is been type casted into dictionary output is in the form of dictionary

sorted_d = dict( sorted(d.items(), key=operator.itemgetter(1),reverse=True))
print('Dictionary in descending order by value : ',sorted_d)

#Write a Python program to add a key to a dictionary.
d={"name":"jerin","age":24}
print(d)
d.update({'email':"jerin@gmail.com"})
print(d)
d["name"]='Jerry'
print(d)
d["city"]='Kalyan'
print(d)
print(d['city'])  #checking values with the key assigned to them
d.update({'state':'Maharashtra'}) #inserting value in dictionary using update keyword
print(d)

#Write a Python program to concatenate following dictionaries to create a new one.
d1={1:10,2:20}
d2={3:30,4:40}
#d3=d1+d2 dictionary does not support arthimatic operations
d3={5:50,6:60}
d4={}
for d in (d1,d2,d3):
  d4.update(d)
print(d4)

#Write a Python program to check whether a given key already exists in a dictionary.
d={1: 10, 2: 20, 3: 30, 4: 40, 5: 50, 6: 60}
counter=0
n=int(input("Enter the key you wish to check: "))
for i in d:
  if i==n:
    counter+=1
if counter==1:
  print("key ",n," is present in the dictionary")
else:
    print("key ",n," is not present in the dictionary")

#Write a Python program to check whether a given value already exists in a dictionary.
d={1: 10, 2: 20, 3: 30, 4: 40, 5: 50, 6: 60}
counter=0
n=int(input("Enter the value you wish to check: "))
for i in d.values():
  if i==n:
    counter+=1
if counter==1:
  print("value ",n," is present in the dictionary")
else:
    print("value ",n," is not present in the dictionary")

#Write a Python program to check whether a given key already exists in a dictionary.
d = {1: 10, 2: 20, 3: 30, 4: 40, 5: 50, 6: 60}
def is_key_present(x):
  if x in d:      #if can also be used as a iteration
      print('Key is present in the dictionary')
  else:
      print('Key is not present in the dictionary')
is_key_present(5)
is_key_present(9)

#Write a Python program to iterate over dictionaries using for loops.

d = {1: 10, 2: 20, 3: 30, 4: 40, 5: 50, 6: 60}
for i,y in d.items():
  print(i,"-->",y)

#Write a Python script to generate and print a dictionary that contains a number (between 1 and n) in the form (x, x*x).

n=int(input("Input a number: "))
d=dict()

for i in range(1,n+1):
  d[i]=i*i

print(d)

#Write a Python script to print a dictionary where the keys are numbers between 1 and 15 (both included) and the values are square of keys.
d=dict()
for x in range(1,16):
    d[x]=x**2
print(d)

#Write a Python script to merge two Python dictionaries.
d1 = {'a': 100, 'b': 200}
d2 = {'x': 300, 'y': 200}
d = d1.copy()  #deep copy applied here
d.update(d2)
print(d)

#Write a Python script to merge two Python dictionaries.
def merge_dictionaries(*dicts): #variable arguments passed here *args
  result = dict()
  for d in dicts:
    result.update(d)
  return result
students1 = {
  'Theodore': 10,
  'Mathew': 11,
}
students2 = {
  'Roxanne': 9
}
print("Original dictionaries:")
print(students1)
print(students2)
print("\nMerge dictionaries:")
print(merge_dictionaries(students1, students2))

#Write a Python program to iterate over dictionaries using for loops.
d={1:'Red',2:'Black',3:'Blue',4:'Yellow'}
for i,j in d.items():
  print('dict key is:',i,' & value is :',j)

#Write a Python program to sum all the items in a dictionary.
d={1:'Red',2:'Black',3:'Blue',4:'Yellow'}
sum=0
for i in d:
  sum+=i
print("sum of key in dictionary is :",sum)

#Write a Python program to sum all the items in a dictionary.
d={'Red':1,'Black':2,'Blue':3,'Yellow':4}
sum=0
for i in d:
  sum+=d[i]
print("sum of values in dictionary is :",sum)