# -*- coding: utf-8 -*-
"""List_DS_Programs.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gx7CcZvpcFQ6ToAY9gcZrUQoIAZ5Tice
"""

emp = ["John", 102, "USA"]     
Dep1 = ["CS",10]  
Dep2 = ["IT",11]    
HOD_CS = [10,"Mr. Holding"]    
HOD_IT = [11, "Mr. Bewon"]    
print("printing employee data...")    
print("Name : %s, ID: %d, Country: %s"%(emp[0],emp[1],emp[2]))    
print("printing departments...")   
print("Department 1:\nName: %s, ID: %d\nDepartment 2:\nName: %s, ID: %s"%(Dep1[0],Dep2[1],Dep2[0],Dep2[1]))    
print("HOD Details ....")    
print("CS HOD Name: %s, Id: %d"%(HOD_CS[1],HOD_CS[0]))    
print("IT HOD Name: %s, Id: %d"%(HOD_IT[1],HOD_IT[0]))    
print(type(emp),type(Dep1),type(Dep2),type(HOD_CS),type(HOD_IT))

#Declaring the empty list  
l =[]  
#Number of elements will be entered by the user    
n = int(input("Enter the size of the list you want: "))  
# for loop to take the input  
for i in range(0,n):     
    # The input is taken from the user and added to the list as the item  
    l.append(input("Enter the item:"))     
print("printing the list items..")   
# traversal loop to print the list items    
for i in l:   
    print(i, end = "  ")

list = [0,1,2,3,4]     
print("printing original list: ");    
for i in list:    
    print(i,end=" ")    
list.remove(2)    
print("\nprinting the list after the removal of first element...")    
for i in list:    
    print(i,end=" ")

#	list(seq) 	It converts any sequence to the list.
str1 = "Johnson"
s = list(str1)
print(type(s))
for i in s:
  print(i)#,end='')

#Example: 1- Write the program to remove the duplicate element of the list.

list1 = [1,2,2,3,55,98,65,65,13,29]  
# Declare an empty list that will store unique values  
list2 = []  
for i in list1:  
    if i not in list2:  
        list2.append(i)  
print(list2)

#Example: 3- Write the program to find the lists consist of at least one common element.

list1 = [1,2,3,4,5,6]  
list2 = [7,8,9,2,10]  
for x in list1:  
    for y in list2:  
        if x == y:  
            print("The common element is:",x)

"""Write a Python program to sum all the items in a list."""

def sum_list(items):
    sum_numbers = 0
    for x in items:
        sum_numbers += x
    return sum_numbers
print(sum_list([1,2,-8]))

"""Write a Python program to multiplies all the items in a list."""

l=[]
mul=1
while True:
  data=input("Enter values: ")
  if data=='':
    break
  l.append(data)
for i in l:
  mul*=int(i)
print("The multiplication of elements of the list is:",mul)

"""Write a Python program to get the largest number from a list."""

l=[]
max=0
while True:
  data=input("Enter values: ")
  if data=='':
    break
  l.append(data)

for i in l:
  if int(i)>max:
    max=int(i)
print("The largest number from the list is: ",max)

"""Write a Python program to get the smallest number from a list."""

l=[]
min=0
while True:
  data=input("Enter values: ")
  if data=='':
    break
  l.append(data)
for i in l:
  if int(i)<min:
    min=int(i)
print("The smallest number from the list is: ",min)

def smallest_num_in_list( list ):
    min = list[ 0 ]
    for a in list:
        if a < min:
            min = a
    return min
print(smallest_num_in_list([1, 2, -8, 0]))

"""Write a Python program to count the number of strings where the string length is 2 or more and the first and last character are same from a given list of strings."""

def match_words(words):
  ctr = 0

  for word in words:
    if len(word) > 1 and word[0] == word[-1]:
      ctr += 1
  return ctr

print(match_words(['abc', 'xyz', 'aba', '1221']))

l = [(2, 5), (1, 2), (4, 4), (2, 3), (2, 1)]

for i in range(len(l)):
  for j in range(len(l)):
    if j!=len(l)-1 and l[j][1] > l[j+1][1]:
      l[j],l[j+1]=l[j+1],l[j]

print(l)

"""Write a Python program to find the list of words that are longer than n from a given list of words."""

def long_words(n, str):
    word_len = []
    txt = str.split(" ")
    for x in txt:
        if len(x) > n:
            word_len.append(x)
    return word_len	
print(long_words(3, "The quick brown fox jumps over the lazy dog"))

"""Write a Python function that takes two lists and returns True if they have at least one common member."""

def common_data(list1, list2):
     result = False
     for x in list1:
         for y in list2:
             if x == y:
                 result = True
                 return result
print(common_data([1,2,3,4,5], [5,6,7,8,9]))
print(common_data([1,2,3,4,5], [6,7,8,9]))

array = [[ ['*' for col in range(6)] for col in range(4)] for row in range(3)]
print(array)

"""Write a Python program to remove duplicates from a list."""

a=[10,20,30,20,10,50,60,40,80,50,40]

dup_items=set()
uniq_items=[]

for i in a:
  if i not in dup_items:
    dup_items.add(i)
    uniq_items.append(i)

print(uniq_items)

"""Write a Python program to check a list is empty or not."""

l = []
if not l:
  print("List is empty")
else:
  print("List contains elements")

"""Write a Python program to clone or copy a list."""

original_list = [10, 22, 44, 23, 4]
new_list2 = list(original_list)
new_list = original_list #shallow copy
new_list1=original_list.copy() #deep copy
print(original_list)
print(new_list1)
print(new_list1)

"""Write a Python program to print a specified list after removing the 0th, 4th and 5th elements."""

color = ['Red', 'Green', 'White', 'Black', 'Pink', 'Yellow']
color = [x for (i,x) in enumerate(color) if i not in (0,4,5)]
print(color)

"""Write a Python program to print the numbers of a specified list after removing even numbers from it."""

num = [7,8, 120, 25, 44, 20, 27]
num = [x for x in num if x%2!=0]
print(num)

"""Write a Python program to shuffle and print a specified list."""

from random import shuffle
color = ['Red', 'Green', 'White', 'Black', 'Pink', 'Yellow']
shuffle(color)
print(color)

"""Write a Python program to generate and print a list of first and last 5 elements where the values are square of numbers between 1 and 30 (both included)."""

def printValues():
	l = list()
	for i in range(1,21):
		l.append(i**2)
	print(l[:5])  
	print(l[-5:])

printValues()

"""Write a Python program to generate and print a list except for the first 5 elements, where the values are square of numbers between 1 and 30 (both included)."""

def printValues():
	l = list()
	for i in range(1,31):
		l.append(i**2)
	print(l[5:])
printValues()

"""Write a Python program to generate all permutations of a list in Python."""

#Itertool is a module provided by Python for creating iterators for efficient looping. 
#Itertools.permutation() function falls under the Combinatoric Generators. 
#The recursive generators that are used to simplify combinatorial constructs such as permutations, combinations, and Cartesian products are called combinatoric iterators.

import itertools
print(list(itertools.permutations([1,2,3])))

"""Write a Python program to get the difference between the two lists."""

list1 = [1, 3, 5, 7, 9]
list2=[1, 2, 4, 6, 7, 8]
diff_list1_list2 = list(set(list1) - set(list2))
diff_list2_list1 = list(set(list2) - set(list1))
total_diff = diff_list1_list2 + diff_list2_list1
print(total_diff)

"""Write a Python program access the index of a list."""

nums = [5, 15, 35, 8, 98]
for num_index, num_val in enumerate(nums):
    print(num_index, num_val)